[package]
name = "event_camera_edit_proto"
version = "0.1.0"
authors = ["David Wood <hello.david.wood@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
include = ["LICENSE-APACHE", "LICENSE-MIT", "**/*.rs", "Cargo.toml"]
rust-version = "1.95"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[dependencies]
iced = "0.14.0"
log = "0.4.27"

# You only need serde if you want app persistence:
serde = { version = "1.0.219", features = ["derive"] }


# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
